# Generated by Django 2.1.3 on 2018-12-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('deprecation', models.CharField(blank=True, max_length=20, null=True)),
                ('assembly_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.Products')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costumes',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.Products')),
                ('decription', models.CharField(max_length=128)),
                ('namufacturer', models.CharField(blank=True, max_length=32, null=True)),
                ('fabric', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('size', models.CharField(max_length=16)),
                ('category', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='manager',
            field=models.ForeignKey(db_column='manager', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
