# Generated by Django 2.1.3 on 2018-12-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181203_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumes',
            old_name='namufacturer',
            new_name='manufacturer',
        ),
    ]
